<?php
/**
 * ACF helper functions
 */

// change / add to the background choices here
$background_choices_available = array (
	'none' 		=> 'No background',
	'inverse' 	=> 'Inverse',
	'bright'	=> 'Bright background',
);

$color_theme_list = array (
	'none' 		=> 'theme 1',
	'inverse' 	=> 'two',
	'bright'	=> 'third',
);

// settings on where the 'sections' are active throughout the site
$where_sections_are_active = array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'portfolio',
		),
	),
/*	add any additional post types here. */
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'person',
		),
	),
);

if( function_exists('acf_add_local_field_group') ):

	//***************************************   PERSON DETAILS

	acf_add_local_field_group(array (
		'key' => 'group_5890531278963',
		'title' => 'Person Details',
		'fields' => array (
			array (
				'key' => 'field_5890580117656',
				'label' => 'Photo',
				'name' => 'person_photo',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_5890531b1046d',
				'label' => 'Position',
				'name' => 'person_position',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_589223e3f5750',
				'label' => 'Short Bio',
				'name' => 'person_short_bio',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'new_lines' => 'wpautop',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => 5,
			),
			array (
				'key' => 'field_5890588717657',
				'label' => 'Profile Type',
				'name' => 'simple_or_extended_profile',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'simple' => 'Simple Profile',
					'extended' => 'Extended Profile',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'simple',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_589bac059cfd9',
				'label' => 'Associated User',
				'name' => 'person_associated_user',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'role' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_58905ace1765b',
				'label' => 'Person\'s First Name',
				'name' => 'person_first_name',
				'type' => 'text',
				'instructions' => 'If you need filtering or sorting by first name.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5890588717657',
							'operator' => '==',
							'value' => 'extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58905b331765c',
				'label' => 'Person\'s Last Name',
				'name' => 'person_last_name',
				'type' => 'text',
				'instructions' => 'If you need filtering or sorting by last name.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5890588717657',
							'operator' => '==',
							'value' => 'extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5890599317658',
				'label' => 'Additional Fields',
				'name' => 'person_additional_fields',
				'type' => 'repeater',
				'instructions' => 'Add additional details. Fill out the label and the content for each.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5890588717657',
							'operator' => '==',
							'value' => 'extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Detail',
				'collapsed' => 'field_58905a4117659',
				'sub_fields' => array (
					array (
						'key' => 'field_58905a4117659',
						'label' => 'Detail Label',
						'name' => 'detail_label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_58905a611765a',
						'label' => 'Detail Content',
						'name' => 'detail_content',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '60',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'new_lines' => 'wpautop',
						'maxlength' => '',
						'placeholder' => '',
						'rows' => 3,
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'excerpt',
			1 => 'custom_fields',
			2 => 'author',
			3 => 'format',
			4 => 'featured_image',
			5 => 'categories',
			6 => 'tags',
		),
		'active' => 1,
		'description' => '',
	));

/*	//***************************************   PAGE SECTIONS
	acf_add_local_field_group(array (
		'key' => 'group_58ec5338d51db',
		'title' => 'Page Sections',
		'fields' => array (
			array (
				'key' => 'field_58ec5338dfb50',
				'label' => 'Sections',
				'name' => 'page_section',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_58ec5338e213a',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add a section',
				'sub_fields' => array (
					array (
						'key' => 'field_58ec5338e213a',
						'label' => 'Section title',
						'name' => 'section_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '85',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_58ec5338e2168',
						'label' => 'Display title?',
						'name' => 'display_title',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array (
						'key' => 'field_58ec5338e2191',
						'label' => 'Background',
						'name' => 'section_background',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'choices' => $background_choices_available,
						'default_value' => array (
							0 => 'none',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array (
						'key' => 'field_58ec5338e21ae',
						'label' => 'Section type',
						'name' => 'section_type',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '100',
							'class' => '',
							'id' => '',
						),

						//*********  LAYOUTS
						'layouts' => array (

							//*********  section layout :  NONE
							'592e3b80783c5' => array (
								'key' => '592e3b80783c5',
								'name' => 'none',
								'label' => 'None',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_592e3b8d783c6',
										'label' => 'No section, just the title',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'nothing to see here. :)',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  HERO
							'58ec4b1a295a8' => array (
								'key' => '58ec4b1a295a8',
								'name' => 'hero',
								'label' => 'Hero',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_58ec4b90c58af',
										'label' => 'Hero text',
										'name' => 'hero_text',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '65',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 5,
										'new_lines' => 'wpautop',
									),
									array (
										'key' => 'field_58ec4bb0c58b0',
										'label' => 'Hero image',
										'name' => 'hero_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '35',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array (
										'key' => 'field_58ec4bf0c58b1',
										'label' => 'Button link',
										'name' => 'hero_button_link',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '65',
											'class' => '',
											'id' => '',
										),
										'post_type' => array (
										),
										'taxonomy' => array (
										),
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
									array (
										'key' => 'field_58ec4c1fc58b2',
										'label' => 'Button label',
										'name' => 'hero_button_label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '35',
											'class' => '',
											'id' => '',
										),
										'default_value' => 'Learn More',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  TEXT / IMAGE GRID
							'59135332400a3' => array (
								'key' => '59135332400a3',
								'name' => 'text_image_grid',
								'label' => 'Text & Image / pattern grid',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_59135384400a4',
										'label' => 'Layout order',
										'name' => 'layout_order',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'image-text' => 'Image/pattern (left) - Text (right)',
											'text-image' => 'Text (left) -	Image/pattern (right)',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'image-text',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_59135468400a5',
										'label' => 'Layout dimensions',
										'name' => 'layout_dimensions',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'half' => 'Half & half (50%)',
											'thirds' => 'Thirds (25% - 75%)',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'half',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_591354f2400a6',
										'label' => 'Text side',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array (
										'key' => 'field_59135504400a7',
										'label' => 'Content',
										'name' => 'text_image_grid_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
									array (
										'key' => 'field_5913555c400a8',
										'label' => 'Image/pattern side',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array (
										'key' => 'field_59135577400a9',
										'label' => 'Image',
										'name' => 'text_image_grid_image',
										'type' => 'image',
										'instructions' => 'leave blank to just keep the pattern visible',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  PAGE GRID
							'58ec4c4ec58b3' => array (
								'key' => '58ec4c4ec58b3',
								'name' => 'page_grid',
								'label' => 'Page grid',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_58ec4c6dc58b4',
										'label' => 'Intro text',
										'name' => 'page_grid_intro_text',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'wpautop',
									),
									array (
										'key' => 'field_58ec4c9dc58b5',
										'label' => 'Page select',
										'name' => 'page_grid_page',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'table',
										'button_label' => 'Add a page',
										'sub_fields' => array (
											array (
												'key' => 'field_58ec4d08c58b6',
												'label' => 'Page select',
												'name' => 'page_select',
												'type' => 'page_link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '30',
													'class' => '',
													'id' => '',
												),
												'post_type' => array (
												),
												'taxonomy' => array (
												),
												'allow_null' => 0,
												'allow_archives' => 1,
												'multiple' => 0,
											),
											array (
												'key' => 'field_592f39f3012ae',
												'label' => 'Page title override',
												'name' => 'page_title_override',
												'type' => 'text',
												'instructions' => '*Optional* way to override the default page title.',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '40',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_58ec4d5dc58b7',
												'label' => 'Background image',
												'name' => 'background_image',
												'type' => 'image',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '30',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'url',
												'preview_size' => 'thumbnail',
												'library' => 'all',
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
											),
										),
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  3 COLUMNS
							'58ec4dc2c58b8' => array (
								'key' => '58ec4dc2c58b8',
								'name' => 'three_col',
								'label' => 'Three columns',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_58ec4dc2c58b9',
										'label' => 'Intro text',
										'name' => 'three_col_intro_text',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 4,
										'new_lines' => 'wpautop',
									),
									array (
										'key' => 'field_58ec4e0fc58bd',
										'label' => 'Column 1',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array (
										'key' => 'field_592e4885977a5',
										'label' => 'Column 1 background?',
										'name' => 'column_1_background_select',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '30',
											'class' => '',
											'id' => '',
										),
										'choices' => $background_choices_available,
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'none',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_592e48a7977a6',
										'label' => 'Background pattern',
										'name' => 'column_1_background_pattern',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e4885977a5',
													'operator' => '==',
													'value' => 'pattern',
												),
											),
										),
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'none' => 'No background',
											'inverse' => 'Inverse',
										),
										'default_value' => array (
											0 => 'none',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
									array (
										'key' => 'field_592e48be977a7',
										'label' => 'Background image',
										'name' => 'column_1_background_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e4885977a5',
													'operator' => '==',
													'value' => 'image',
												),
											),
										),
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array (
										'key' => 'field_592e48d8977a8',
										'label' => 'Show button (col1)?',
										'name' => 'column_1_show_button_select',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array (
										'key' => 'field_58ec4e43c58be',
										'label' => 'Column 1 title',
										'name' => 'column_1_title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_58ec4e61c58bf',
										'label' => 'Column 1 content',
										'name' => 'column_1_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 1,
									),
									array (
										'key' => 'field_58ec4e9ac58c1',
										'label' => 'Button link',
										'name' => 'column_1_link',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e48d8977a8',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '65',
											'class' => '',
											'id' => '',
										),
										'post_type' => array (
										),
										'taxonomy' => array (
										),
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
									array (
										'key' => 'field_58ec4ec4c58c2',
										'label' => 'Button label',
										'name' => 'column_1_button_label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e48d8977a8',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '35',
											'class' => '',
											'id' => '',
										),
										'default_value' => 'Learn More',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_58ec4ef8c58c3',
										'label' => 'Column 2',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array (
										'key' => 'field_592e464aa2d3b',
										'label' => 'Column 2 background?',
										'name' => 'column_2_background_select',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '30',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'none' => 'None',
											'pattern' => 'Pattern',
											'image' => 'Image',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'none',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_592e465da2d3c',
										'label' => 'Background pattern',
										'name' => 'column_2_background_pattern',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e464aa2d3b',
													'operator' => '==',
													'value' => 'pattern',
												),
											),
										),
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'choices' => $background_choices_available,
										'default_value' => array (
											0 => 'none',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
									array (
										'key' => 'field_592e4674a2d3d',
										'label' => 'Background image',
										'name' => 'column_2_background_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e464aa2d3b',
													'operator' => '==',
													'value' => 'image',
												),
											),
										),
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array (
										'key' => 'field_592e4696a2d3e',
										'label' => 'Show button (col2)?',
										'name' => 'column_2_show_button_select',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array (
										'key' => 'field_58ec4f10c58c4',
										'label' => 'Column 2 title',
										'name' => 'column_2_title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_58ec4f27c58c5',
										'label' => 'Column 2 content',
										'name' => 'column_2_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 1,
									),
									array (
										'key' => 'field_58ec4f3dc58c6',
										'label' => 'Button link',
										'name' => 'column_2_link',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e4696a2d3e',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '65',
											'class' => '',
											'id' => '',
										),
										'post_type' => array (
										),
										'taxonomy' => array (
										),
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
									array (
										'key' => 'field_58ec4f51c58c7',
										'label' => 'Button label',
										'name' => 'column_2_button_label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e4696a2d3e',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '35',
											'class' => '',
											'id' => '',
										),
										'default_value' => 'Learn More',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_58ec4f67c58c8',
										'label' => 'Column 3',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array (
										'key' => 'field_592e4386a2d37',
										'label' => 'Column 3 background?',
										'name' => 'column_3_background_select',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '30',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'none' => 'None',
											'pattern' => 'Pattern',
											'image' => 'Image',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'none',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_592e451ba2d38',
										'label' => 'Background pattern',
										'name' => 'column_3_background_pattern',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e4386a2d37',
													'operator' => '==',
													'value' => 'pattern',
												),
											),
										),
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'choices' => $background_choices_available,
										'default_value' => array (
											0 => 'none',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
									array (
										'key' => 'field_592e4588a2d39',
										'label' => 'Background image',
										'name' => 'column_3_background_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e4386a2d37',
													'operator' => '==',
													'value' => 'image',
												),
											),
										),
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array (
										'key' => 'field_592e45b9a2d3a',
										'label' => 'Show button (col3)?',
										'name' => 'column_3_show_button_select',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array (
										'key' => 'field_58ec4fbcc58cc',
										'label' => 'Column 3 title',
										'name' => 'column_3_title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array (
										'key' => 'field_58ec4fb9c58cb',
										'label' => 'Column 3 content',
										'name' => 'column_3_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 1,
									),
									array (
										'key' => 'field_58ec4f96c58ca',
										'label' => 'Button link',
										'name' => 'column_3_link',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e45b9a2d3a',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '65',
											'class' => '',
											'id' => '',
										),
										'post_type' => array (
										),
										'taxonomy' => array (
										),
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
									array (
										'key' => 'field_58ec4f7ec58c9',
										'label' => 'Button label',
										'name' => 'column_3_button_label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_592e45b9a2d3a',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array (
											'width' => '35',
											'class' => '',
											'id' => '',
										),
										'default_value' => 'Learn More',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  CONTENT COLLECTION
							'584f2e841870b' => array (
								'key' => '584f2e841870b',
								'name' => 'content_collection',
								'label' => 'Content Collection',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_584f2e9f1870c',
										'label' => 'Introduction',
										'name' => 'content_introduction',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 1,
										'default_value' => '',
										'delay' => 0,
									),
									array (
										'key' => 'field_584f2ebe1870d',
										'label' => 'Display Style',
										'name' => 'content_display_style',
										'type' => 'select',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'multiple' => 0,
										'allow_null' => 0,
										'choices' => array (
											'Grid' => 'Grid',
											'List' => 'List',
											'Slider' => 'Slider',
										),
										'default_value' => array (
											0 => 'Grid',
										),
										'ui' => 0,
										'ajax' => 0,
										'placeholder' => '',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_584f2f061870e',
										'label' => 'Collection Type',
										'name' => 'content_collection_type',
										'type' => 'select',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'multiple' => 0,
										'allow_null' => 1,
										'choices' => array (
											'Explicit' => 'Explicit',
											'Generated' => 'Generated',
										),
										'default_value' => array (
											0 => 'Explicit',
										),
										'ui' => 0,
										'ajax' => 0,
										'placeholder' => '',
										'return_format' => 'value',
									),
									array (
										'key' => 'field_584f2faa18710',
										'label' => 'Items to Include',
										'name' => 'content_post_ids',
										'type' => 'relationship',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_584f2f061870e',
													'operator' => '==',
													'value' => 'Explicit',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array (
										),
										'taxonomy' => array (
										),
										'min' => 1,
										'max' => 24,
										'filters' => array (
											0 => 'search',
											1 => 'post_type',
											2 => 'taxonomy',
										),
										'elements' => array (
											0 => 'featured_image',
										),
										'return_format' => 'id',
									),
									array (
										'key' => 'field_584f2ff018711',
										'label' => 'Types to Include',
										'name' => 'content_post_types',
										'type' => 'checkbox',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_584f2f061870e',
													'operator' => '==',
													'value' => 'Generated',
												),
											),
										),
										'wrapper' => array (
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'layout' => 'vertical',
										'choices' => array (
											'post' => 'Posts',
											'page' => 'Pages',
											'attachment' => 'Media',
										),
										'default_value' => array (
										),
										'allow_custom' => 0,
										'save_custom' => 0,
										'toggle' => 0,
										'return_format' => 'value',
									),
									array (
										'key' => 'field_584f307818712',
										'label' => 'Limit by Categories',
										'name' => 'content_terms',
										'type' => 'taxonomy',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_584f2f061870e',
													'operator' => '==',
													'value' => 'Generated',
												),
											),
										),
										'wrapper' => array (
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'taxonomy' => 'category',
										'field_type' => 'checkbox',
										'multiple' => 0,
										'allow_null' => 0,
										'return_format' => 'id',
										'add_term' => 0,
										'load_terms' => 0,
										'save_terms' => 0,
									),
									array (
										'key' => 'field_584f30d9d7922',
										'label' => 'Number to Show',
										'name' => 'content_number_shown',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_584f2f061870e',
													'operator' => '==',
													'value' => 'Generated',
												),
											),
										),
										'wrapper' => array (
											'width' => '34',
											'class' => '',
											'id' => '',
										),
										'default_value' => 3,
										'min' => 1,
										'max' => 24,
										'step' => 1,
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  WYSIWYG
							'58ec5009c58cd' => array (
								'key' => '58ec5009c58cd',
								'name' => 'wysiwyg',
								'label' => 'Full width WYSIWYG block',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_58ec5338eca7c',
										'label' => 'Content',
										'name' => 'wysiwyg_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),

							//*********  section layout :  CHILD PAGE GRID
							'592e8d02ede68' => array (
								'key' => '592e8d02ede68',
								'name' => 'child_page_grid',
								'label' => 'Child page grid',
								'display' => 'block',
								'sub_fields' => array (
									array (
										'key' => 'field_592e8d32ede69',
										'label' => 'Display icons?',
										'name' => 'display_icons',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '25',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array (
										'key' => 'field_592e8de6ede6a',
										'label' => 'Display page titles?',
										'name' => 'display_page_titles',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '25',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array (
										'key' => 'field_592e8e0bede6b',
										'label' => 'Display "learn more" buttons',
										'name' => 'display_learn_more_buttons',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '24',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array (
										'key' => 'field_592e8e28ede6c',
										'label' => 'Make them links?',
										'name' => 'make_them_links',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '25',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
						),
						'button_label' => 'Choose section type',
						'min' => '',
						'max' => 1,
					),
				),
			),
		),
		'location' => $where_sections_are_active,
		'menu_order' => 1,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'custom_fields',
			3 => 'discussion',
			4 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));*/

	//***************************************   PERSON CONTACT

	acf_add_local_field_group(array (
		'key' => 'group_58908d6789994',
		'title' => 'Person Contact',
		'fields' => array (
			array (
				'key' => 'field_58908d6f45ded',
				'label' => 'Email Address',
				'name' => 'person_email_address',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58908dcb45dee',
				'label' => 'Phone Number',
				'name' => 'person_phone_number',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58908e0045def',
				'label' => 'Fax',
				'name' => 'person_fax',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58908e7e45df0',
				'label' => 'Social Media Profiles',
				'name' => 'person_social_media',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Link',
				'collapsed' => 'field_58908eb145df1',
				'sub_fields' => array (
					array (
						'key' => 'field_58908eb145df1',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_58908ed245df2',
						'label' => 'Profile Link',
						'name' => 'profile_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'excerpt',
			1 => 'custom_fields',
			2 => 'discussion',
			3 => 'author',
			4 => 'format',
			5 => 'featured_image',
			6 => 'categories',
			7 => 'tags',
		),
		'active' => 1,
		'description' => '',
	));

	//***************************************   SITE OPTIONS

	acf_add_local_field_group(array (
		'key' => 'group_57f7c88c9aa18',
		'title' => 'Site Options',
		'fields' => array (
			array (
				'key' => 'field_57fbf3676e7e9',
				'label' => 'Display Options',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),

			 array(
				'key' => 'field_5a1f1b703a28e',
				'label' => 'Site Logo',
				'name' => 'site_logo',
				'type' => 'image',
				'instructions' => 'Add a logo image for the header. If none, the site name will show in large text.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'jpg, gif, svg, png',
			),

			array (
				'key' => 'field_57f7c92167a96',
				'label' => 'Default Featured Image',
				'name' => 'default_post_thumbnail_id',
				'type' => 'image',
				'instructions' => 'If set, this image will be displayed as the featured image for any posts that don\'t have their own custom featured images.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_57fc43235c0d0',
				'label' => 'Excerpt Settings',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Settings below determine how automatically generated post excerpts (aka blurbs) are displayed: how long they should be, and what text (if any) should be appended to the excerpt as a link to the post itself.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_57fbf44a6e7f0',
				'label' => 'Length',
				'name' => 'excerpt_length',
				'type' => 'number',
				'instructions' => 'Set to 0 to revert to WordPress\'s default (55 words), or to allow another plugin to trim excerpts.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => 40,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57fbf4686e7f1',
				'label' => 'Units',
				'name' => 'excerpt_length_unit',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'words' => 'Words',
					'chars' => 'Characters',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'words',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fc42c5a2686',
				'label' => 'Link Text',
				'name' => 'excerpt_link_text',
				'type' => 'text',
				'instructions' => 'e.g. \'Read more\'. Leave blank for no link.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Read more',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			//
			array (
				'key' => 'field_5a1d8a764a977',
				'label' => 'Colors',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_12358ec5338e2191',
				'label' => 'Color Theme',
				'name' => 'color_theme',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'choices' => $color_theme_list,
				'default_value' => array (
					0 => 'none',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),


			array (
				'key' => 'field_1235890588717657',
				'label' => 'Color Theme',
				'name' => 'color_theme_or_custom_choice',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'color_theme' => 'Choose from library',
					'custom' => 'Custom colors',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'color_theme',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_5a1d8a994a978',
				'label' => 'Base colors',
				'name' => 'base_colors',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5a1d8aae4a979',
						'label' => 'Background color',
						'name' => 'background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5a1d8b844a97a',
						'label' => 'Text color',
						'name' => 'text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#565050',
					),
					array(
						'key' => 'field_5a1d8b944a97b',
						'label' => 'Link color',
						'name' => 'link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#6D7298',
					),
					array(
						'key' => 'field_5a1d8bf64a97c',
						'label' => 'Link hover',
						'name' => 'link_hover',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#565FA3',
					),
				),
			),
			array (
				'key' => 'field_5a1d8e351faec',
				'label' => 'Primary colors',
				'name' => 'primary_colors',
				'type' => 'group',
				'instructions' => 'For use of your main brand color. Text and link colors refer to the text/links on top of the primary brand color',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5a1d8e351faed',
						'label' => 'Primary color',
						'name' => 'background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#FE5F55',
					),
					array(
						'key' => 'field_5a1d8e351faee',
						'label' => 'Text color',
						'name' => 'text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5a1d8e351faef',
						'label' => 'Link color',
						'name' => 'link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#FCE197',
					),
					array(
						'key' => 'field_5a1d8e351faf0',
						'label' => 'Link hover',
						'name' => 'link_hover',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
				),
			),
			array (
				'key' => 'field_5a1d90238a9b7',
				'label' => 'Inverse colors',
				'name' => 'inverse_colors',
				'type' => 'group',
				'instructions' => 'For an "inverse" option of the main/base colors.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5a1d90238a9b8',
						'label' => 'Background color',
						'name' => 'background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#565050',
					),
					array(
						'key' => 'field_5a1d90238a9b9',
						'label' => 'Text color',
						'name' => 'text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5a1d90238a9ba',
						'label' => 'Link color',
						'name' => 'link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#B9D8F7',
					),
					array(
						'key' => 'field_5a1d90238a9bb',
						'label' => 'Link hover',
						'name' => 'link_hover',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
				),
			),
			/*
			array (
				'key' => 'field_5a1d914942cc6',
				'label' => 'Accent colors',
				'name' => 'accent_colors_container',
				'type' => 'group',
				'instructions' => 'Add any additional accent colors',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5a1d91aa42cc7',
						'label' => 'All accent colors',
						'name' => 'accent_color_array',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_5a1d91f142cc9',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => 'Add a color',
						'sub_fields' => array(
							array(
								'key' => 'field_5a1d91f142cc9',
								'label' => 'Accent color',
								'name' => 'accent_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_5a1d91f142cc8',
								'label' => 'Text',
								'name' => 'accent_color_details',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5a1d91f142cca',
										'label' => 'Text color',
										'name' => 'text_color',
										'type' => 'color_picker',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '#565050',
									),
									array(
										'key' => 'field_5a1d91f142ccb',
										'label' => 'Link color',
										'name' => 'link_color',
										'type' => 'color_picker',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '#6D7298',
									),
									array(
										'key' => 'field_5a1d91f142ccc',
										'label' => 'Link hover',
										'name' => 'link_hover',
										'type' => 'color_picker',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '#565FA3',
									),
								),
							),
						),
					),
				),
			),
			*/
			array (
				'key' => 'field_57fbf37a6e7ea',
				'label' => 'Text',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7ceae82de8',
				'label' => 'Contact Info',
				'name' => 'contact_info',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array (
				'key' => 'field_57fbf4cf6e7f2',
				'label' => 'Copyright Text',
				'name' => 'copyright_text',
				'type' => 'text',
				'instructions' => 'The text <code>[year]</code> will be replaced with the current year.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Copyright © [year]. All rights reserved.',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57fbf39a6e7eb',
				'label' => 'URLs',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7ca2067a98',
				'label' => 'Social Media Links',
				'name' => 'social_links',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_57f7ca3567a99',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Service',
				'sub_fields' => array (
					array (
						'key' => 'field_57f7ca3567a99',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'facebook' => 'Facebook',
							'flickr' => 'Flickr',
							'googleplus' => 'Google+',
							'instagram' => 'Instagram',
							'linkedin' => 'LinkedIn',
							'pinterest' => 'Pinterest',
							'snapchat' => 'Snapchat',
							'tumblr' => 'Tumblr',
							'twitter' => 'Twitter',
							'youtube' => 'YouTube',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array (
						'key' => 'field_57f7cb1267a9b',
						'label' => 'Link Text',
						'name' => 'link_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'e.g. "Like us on Facebook", or "@MyOrg"',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57f7caee67a9a',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array (
				'key' => 'field_57fbf3ab6e7ec',
				'label' => 'Integrations/API Keys',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7d17269b71',
				'label' => 'Facebook App ID',
				'name' => 'facebook_app_id',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57f7ca0467a97',
				'label' => 'Google Maps API Key',
				'name' => 'google_maps_api_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'start-site-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1476826847,
	));

	//***************************************   PORTFOLIO DETAILS

	acf_add_local_field_group(array (
		'key' => 'group_590bf408c8e1b',
		'title' => 'Portfolio Details',
		'fields' => array (
			array (
				'key' => 'field_5910044346ab2',
				'label' => 'Project subtitle',
				'name' => 'portfolio_subtitle',
				'type' => 'text',
				'instructions' => 'this is the descriptive text to go under the client name.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590bf40f3263f',
				'label' => 'Site URL',
				'name' => 'portfolio_site_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_590bf43332640',
				'label' => 'Date completed',
				'name' => 'portfolio_date_completed',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590fed8969912',
				'label' => 'Page background',
				'name' => 'page_background',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'none' => 'No background',
					'pattern-grey-1' => 'Grey, with large arrows',
					'pattern-green' => 'Green',
					'pattern-purple' => 'Purple',
					'pattern-teal' => 'Teal',
					'pattern-dark-blue' => 'Dark blue',
					'pattern-orange' => 'Orange',
					'pattern-grey-2' => 'Grey, with multi-colored lines',
					'pattern-gold' => 'Gold',
					'pattern-light' => 'Light',
					'pattern-light-blue' => 'Light blue',
					'granite-texture' => 'Granite',
				),
				'default_value' => array (
					0 => 'none',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array (
				'key' => 'field_598de22892389',
				'label' => 'Featured image frame',
				'name' => 'featured_image_frame',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'no-frame' => 'No frame',
					'browser-frame' => 'Browser frame',
					'browser-frame-no-url' => 'Browser frame, with no URL area',
					'video-frame' => 'Video frame',
					'photo-frame' => 'Photo / print work frame',
				),
				'default_value' => array (
					0 => 'no-frame',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array (
				'key' => 'field_5911fda4e777d',
				'label' => 'Featured?',
				'name' => 'portfolio_featured',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Feature this project',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'custom_fields',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'author',
			7 => 'format',
			8 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));


endif;