<?php
/**
 * ACF helper functions
 */

// change / add to the background choices here
$background_choices_available = array (
	'none' 		=> 'No background',
	'inverse' 	=> 'Inverse',
	'bright'	=> 'Bright background',
);

$color_theme_list = array (
	'none' 		=> 'theme 1',
	'inverse' 	=> 'two',
	'bright'	=> 'third',
);

$nav_font_choices = array(
	'Roboto:wght@500' => 'Roboto',
	'Montserrat:wght@400' => 'Montserrat',
	'Poppins:wght@500' => 'Poppins',
	'Barlow+Condensed:wght@500' => 'Barlow Condensed',
	'Hind:wght@500' => 'Hind',
	'Josefin+Slab:wght@500' => 'Josefin Slab',
	'Noto+Serif:wght@700' => 'Noto Serif',
	'Walter+Turncoat' => 'Walter Turncoat',
);

$heading_font_choices = array(
	'Roboto:ital,wght@0,100;0,700;1,100;1,700' => 'Roboto',
	'Work+Sans:ital,wght@0,200;0,800;1,200;1,800' => 'Work Sans',
	'Poppins:ital,wght@0,200;0,700;1,200;1,700' => 'Poppins',
	'Barlow+Condensed:ital,wght@0,200;0,700;1,200;1,700' => 'Barlow Condensed',
	'Hind:wght@300;700' => 'Hind',
	'Trispace:wght@200;400;800' => 'Trispace',
	'Cormorant+Garamond:ital,wght@0,300;0,700;1,300;1,700' => 'Cormorant Garamond',
	'Josefin+Slab:ital,wght@0,200;0,700;1,200;1,700' => 'Josefin Slab',
	'Architects+Daughter' => 'Architects Daughter',
	'Gaegu:wght@300;700' => 'Gaegu',
	'Nanum+Pen+Script' => 'Nanum Pen Script',
);

$body_font_choices = array(
	'Roboto:ital,wght@0,300;0,900;1,300;1,900' => 'Roboto',
	'Work+Sans:ital,wght@0,300;0,800;1,300;1,800' => 'Work Sans',
	'Montserrat:ital,wght@0,300;0,800;1,300;1,800' => 'Montserrat',
	'Poppins:ital,wght@0,300;0,800;1,300;1,800' => 'Poppins',
	'Noto+Serif:ital,wght@0,400;0,700;1,400;1,700' => 'Noto Serif',
	'Cormorant+Garamond:ital,wght@0,500;0,700;1,500;1,700' => 'Cormorant Garamond',
	'Josefin+Slab:ital,wght@0,400;0,700;1,400;1,700' => 'Josefin Slab',
	'Gaegu:wght@400;700' => 'Gaegu',
);

// settings on where the 'sections' are active throughout the site
$where_sections_are_active = array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'portfolio',
		),
	),
/*	add any additional post types here. */
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'person',
		),
	),
);

if( function_exists('acf_add_local_field_group') ):

	//***************************************   PERSON DETAILS

	acf_add_local_field_group(array (
		'key' => 'group_5890531278963',
		'title' => 'Person Details',
		'fields' => array (
			array (
				'key' => 'field_5890580117656',
				'label' => 'Photo',
				'name' => 'person_photo',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_5890531b1046d',
				'label' => 'Position',
				'name' => 'person_position',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_589223e3f5750',
				'label' => 'Short Bio',
				'name' => 'person_short_bio',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'new_lines' => 'wpautop',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => 5,
			),
			array (
				'key' => 'field_5890588717657',
				'label' => 'Profile Type',
				'name' => 'simple_or_extended_profile',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'simple' => 'Simple Profile',
					'extended' => 'Extended Profile',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'simple',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_589bac059cfd9',
				'label' => 'Associated User',
				'name' => 'person_associated_user',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'role' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_58905ace1765b',
				'label' => 'Person\'s First Name',
				'name' => 'person_first_name',
				'type' => 'text',
				'instructions' => 'If you need filtering or sorting by first name.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5890588717657',
							'operator' => '==',
							'value' => 'extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58905b331765c',
				'label' => 'Person\'s Last Name',
				'name' => 'person_last_name',
				'type' => 'text',
				'instructions' => 'If you need filtering or sorting by last name.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5890588717657',
							'operator' => '==',
							'value' => 'extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5890599317658',
				'label' => 'Additional Fields',
				'name' => 'person_additional_fields',
				'type' => 'repeater',
				'instructions' => 'Add additional details. Fill out the label and the content for each.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5890588717657',
							'operator' => '==',
							'value' => 'extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Detail',
				'collapsed' => 'field_58905a4117659',
				'sub_fields' => array (
					array (
						'key' => 'field_58905a4117659',
						'label' => 'Detail Label',
						'name' => 'detail_label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_58905a611765a',
						'label' => 'Detail Content',
						'name' => 'detail_content',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '60',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'new_lines' => 'wpautop',
						'maxlength' => '',
						'placeholder' => '',
						'rows' => 3,
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'excerpt',
			1 => 'custom_fields',
			2 => 'author',
			3 => 'format',
			4 => 'featured_image',
			5 => 'categories',
			6 => 'tags',
		),
		'active' => 1,
		'description' => '',
	));

	//***************************************   PERSON CONTACT

	acf_add_local_field_group(array (
		'key' => 'group_58908d6789994',
		'title' => 'Person Contact',
		'fields' => array (
			array (
				'key' => 'field_58908d6f45ded',
				'label' => 'Email Address',
				'name' => 'person_email_address',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58908dcb45dee',
				'label' => 'Phone Number',
				'name' => 'person_phone_number',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58908e0045def',
				'label' => 'Fax',
				'name' => 'person_fax',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58908e7e45df0',
				'label' => 'Social Media Profiles',
				'name' => 'person_social_media',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Link',
				'collapsed' => 'field_58908eb145df1',
				'sub_fields' => array (
					array (
						'key' => 'field_58908eb145df1',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_58908ed245df2',
						'label' => 'Profile Link',
						'name' => 'profile_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'excerpt',
			1 => 'custom_fields',
			2 => 'discussion',
			3 => 'author',
			4 => 'format',
			5 => 'featured_image',
			6 => 'categories',
			7 => 'tags',
		),
		'active' => 1,
		'description' => '',
	));

	//***************************************   SITE OPTIONS

	acf_add_local_field_group(array (
		'key' => 'group_57f7c88c9aa18',
		'title' => 'Site Options',
		'fields' => array (
			array (
				'key' => 'field_57fbf3676e7e9',
				'label' => 'Display Options',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),

			 array(
				'key' => 'field_5a1f1b703a28e',
				'label' => 'Site Logo',
				'name' => 'site_logo',
				'type' => 'image',
				'instructions' => 'Add a logo image for the header. If none, the site name will show in large text.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'jpg, gif, svg, png',
			),

			array (
				'key' => 'field_57f7c92167a96',
				'label' => 'Default Featured Image',
				'name' => 'default_post_thumbnail_id',
				'type' => 'image',
				'instructions' => 'If set, this image will be displayed as the featured image for any posts that don\'t have their own custom featured images.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_57fc43235c0d0',
				'label' => 'Excerpt Settings',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Settings below determine how automatically generated post excerpts (aka blurbs) are displayed: how long they should be, and what text (if any) should be appended to the excerpt as a link to the post itself.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_57fbf44a6e7f0',
				'label' => 'Length',
				'name' => 'excerpt_length',
				'type' => 'number',
				'instructions' => 'Set to 0 to revert to WordPress\'s default (55 words), or to allow another plugin to trim excerpts.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => 40,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57fbf4686e7f1',
				'label' => 'Units',
				'name' => 'excerpt_length_unit',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'words' => 'Words',
					'chars' => 'Characters',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'words',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fc42c5a2686',
				'label' => 'Link Text',
				'name' => 'excerpt_link_text',
				'type' => 'text',
				'instructions' => 'e.g. \'Read more\'. Leave blank for no link.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Read more',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),

			array (
				'key' => 'field_5a1d8a764a977',
				'label' => 'Theme Design',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),



			array (
				'key' => 'field_1235890588717657',
				'label' => 'Theme Design',
				'name' => 'color_theme_or_custom_choice',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'color_theme' => 'Choose from library',
					'custom' => 'Custom',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'color_theme',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),

			array (
				'key' => 'field_12358ec5338e2191',
				'label' => 'Theme library',
				'name' => 'color_theme',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'color_theme',
						),
					),
				),
				'wrapper' => array (
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'choices' => $color_theme_list,
				'default_value' => array (
					0 => 'none',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),

			array(
				'key' => 'field_5ff4c898f375b',
				'label' => 'Page Header',
				'name' => 'page_header_design',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4c8fef375c',
						'label' => 'Header background color',
						'name' => 'header_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5ff4c9aaf375d',
						'label' => 'Header text color',
						'name' => 'header_text_color',
						'type' => 'color_picker',
						'instructions' => 'If no site logo is added, your site name will be this color.

Make sure this text color is readable on your header background color',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4caa6f375e',
						'label' => 'Top navigation bar background color',
						'name' => 'top_navigation_bar_background_color_choice',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none' => 'Same as page header',
							'custom' => 'Custom color',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'none',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ff4e46ac33be',
						'label' => 'Top nav bar background',
						'name' => 'top_nav_bar_background',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ff4caa6f375e',
									'operator' => '==',
									'value' => 'custom',
								),
							),
						),
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
				),
			),
			array(
				'key' => 'field_5ff4cbff13392',
				'label' => 'Top Navigation Bar',
				'name' => 'top_navigation_bar_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4cc3113393',
						'label' => 'Nav item background color',
						'name' => 'nav_item_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d0ebff',
					),
					array(
						'key' => 'field_5ff4cc8713394',
						'label' => 'Nav item text color',
						'name' => 'nav_item_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4cca613395',
						'label' => 'Hover background color',
						'name' => 'nav_item_hover_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4ccaa13396',
						'label' => 'Hover text color',
						'name' => 'nav_item_hover_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d0ebff',
					),
					array(
						'key' => 'field_5ff4db6b13397',
						'label' => 'Nav item font',
						'name' => 'nav_item_font',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'choices' => $nav_font_choices,
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_5ff4dc2bb571b',
				'label' => 'Page Body',
				'name' => 'page_body_design',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4dc3db571c',
						'label' => 'Page background color',
						'name' => 'page_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5ff4dcc4b571d',
						'label' => 'Text color',
						'name' => 'page_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#212529',
					),
					array(
						'key' => 'field_5ff4dd00b571e',
						'label' => 'Link color',
						'name' => 'page_link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#1864ab',
					),
					array(
						'key' => 'field_5ff4dd12b571f',
						'label' => 'Link hover color',
						'name' => 'page_link_hover_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#5f3dc4',
					),
					array(
						'key' => 'field_5ff4dd3bb5720',
						'label' => 'Body text font',
						'name' => 'body_text_font',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '80',
							'class' => '',
							'id' => '',
						),
						'choices' => $body_font_choices,
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ff4dd9ab5721',
						'label' => 'Default size',
						'name' => 'body_text_default_size',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 21,
						'placeholder' => '',
						'prepend' => '',
						'append' => 'pt',
						'min' => 12,
						'max' => 30,
						'step' => -13,
					),
					array(
						'key' => 'field_5ff4e24dcff0b',
						'label' => 'Heading text font',
						'name' => 'page_heading_text_font',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '80',
							'class' => '',
							'id' => '',
						),
						'choices' => $heading_font_choices,
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ff4e29dcff0c',
						'label' => 'Bold page title?',
						'name' => 'bold_page_title',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Yes' => 'Yes',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5ff4ddddb5722',
						'label' => 'Primary button: background color',
						'name' => 'primary_button_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d9480f',
					),
					array(
						'key' => 'field_5ff4de19b5723',
						'label' => 'Primary button: text color',
						'name' => 'primary_button_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_5ff4de32b5724',
						'label' => 'Primary button: hover background color',
						'name' => 'primary_button_hover_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#a61e4d',
					),
					array(
						'key' => 'field_5ff4de64b5725',
						'label' => 'Primary button: hover text color',
						'name' => 'primary_button_hover_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),

					array(
						'key' => 'field_115ff4ddddb5722',
						'label' => 'Secondary button: background color',
						'name' => 'secondary_button_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#4dabf7',
					),
					array(
						'key' => 'field_115ff4de19b5723',
						'label' => 'Secondary button: text color',
						'name' => 'secondary_button_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
					array(
						'key' => 'field_115ff4de32b5724',
						'label' => 'Secondary button: hover background color',
						'name' => 'secondary_button_hover_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#20c997',
					),
					array(
						'key' => 'field_115ff4de64b5725',
						'label' => 'Secondary button: hover text color',
						'name' => 'secondary_button_hover_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ffffff',
					),
				),
			),
			array(
				'key' => 'field_5ff4deb389975',
				'label' => 'Page Footer',
				'name' => 'page_footer_design',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_1235890588717657',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ff4deb389976',
						'label' => 'Footer background color',
						'name' => 'footer_background_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#212529',
					),
					array(
						'key' => 'field_5ff4deb389977',
						'label' => 'Footer text color',
						'name' => 'footer_text_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ced4da',
					),
					array(
						'key' => 'field_5ff4deb389978',
						'label' => 'Footer link color',
						'name' => 'footer_link_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#d0ebff',
					),
					array(
						'key' => 'field_5ff4deb389979',
						'label' => 'Footer link hover color',
						'name' => 'footer_link_hover_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#ced4da',
					),
				),
			),

			array (
				'key' => 'field_57fbf37a6e7ea',
				'label' => 'Text',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7ceae82de8',
				'label' => 'Contact Info',
				'name' => 'contact_info',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array (
				'key' => 'field_57fbf4cf6e7f2',
				'label' => 'Copyright Text',
				'name' => 'copyright_text',
				'type' => 'text',
				'instructions' => 'The text <code>[year]</code> will be replaced with the current year.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Copyright © [year]. All rights reserved.',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57fbf39a6e7eb',
				'label' => 'URLs',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7ca2067a98',
				'label' => 'Social Media Links',
				'name' => 'social_links',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_57f7ca3567a99',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Service',
				'sub_fields' => array (
					array (
						'key' => 'field_57f7ca3567a99',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'facebook' => 'Facebook',
							'flickr' => 'Flickr',
							'googleplus' => 'Google+',
							'instagram' => 'Instagram',
							'linkedin' => 'LinkedIn',
							'pinterest' => 'Pinterest',
							'snapchat' => 'Snapchat',
							'tumblr' => 'Tumblr',
							'twitter' => 'Twitter',
							'youtube' => 'YouTube',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array (
						'key' => 'field_57f7cb1267a9b',
						'label' => 'Link Text',
						'name' => 'link_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'e.g. "Like us on Facebook", or "@MyOrg"',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57f7caee67a9a',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array (
				'key' => 'field_57fbf3ab6e7ec',
				'label' => 'Integrations/API Keys',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_57f7d17269b71',
				'label' => 'Facebook App ID',
				'name' => 'facebook_app_id',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57f7ca0467a97',
				'label' => 'Google Maps API Key',
				'name' => 'google_maps_api_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'start-site-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1476826847,
	));

	//***************************************   PORTFOLIO DETAILS

	acf_add_local_field_group(array (
		'key' => 'group_590bf408c8e1b',
		'title' => 'Portfolio Details',
		'fields' => array (
			array (
				'key' => 'field_5910044346ab2',
				'label' => 'Project subtitle',
				'name' => 'portfolio_subtitle',
				'type' => 'text',
				'instructions' => 'this is the descriptive text to go under the client name.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590bf40f3263f',
				'label' => 'Site URL',
				'name' => 'portfolio_site_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_590bf43332640',
				'label' => 'Date completed',
				'name' => 'portfolio_date_completed',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590fed8969912',
				'label' => 'Page background',
				'name' => 'page_background',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'none' => 'No background',
					'pattern-grey-1' => 'Grey, with large arrows',
					'pattern-green' => 'Green',
					'pattern-purple' => 'Purple',
					'pattern-teal' => 'Teal',
					'pattern-dark-blue' => 'Dark blue',
					'pattern-orange' => 'Orange',
					'pattern-grey-2' => 'Grey, with multi-colored lines',
					'pattern-gold' => 'Gold',
					'pattern-light' => 'Light',
					'pattern-light-blue' => 'Light blue',
					'granite-texture' => 'Granite',
				),
				'default_value' => array (
					0 => 'none',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array (
				'key' => 'field_598de22892389',
				'label' => 'Featured image frame',
				'name' => 'featured_image_frame',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'no-frame' => 'No frame',
					'browser-frame' => 'Browser frame',
					'browser-frame-no-url' => 'Browser frame, with no URL area',
					'video-frame' => 'Video frame',
					'photo-frame' => 'Photo / print work frame',
				),
				'default_value' => array (
					0 => 'no-frame',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array (
				'key' => 'field_5911fda4e777d',
				'label' => 'Featured?',
				'name' => 'portfolio_featured',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Feature this project',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'custom_fields',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'author',
			7 => 'format',
			8 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));


endif;